version: '3.4'

networks:
  backend:
    driver: bridge

services:
  mediscreendb:
    container_name: ${DB_HOST}
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME}
    ports:
      -  27017:27017
    networks:
      - backend
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mediscreen.gatewayapi:
    container_name: ${GATEWAY_HOST}
    image: ${DOCKER_REGISTRY-}mediscreengatewayapi
    build:
      context: .
      dockerfile: Mediscreen.GatewayAPI/Dockerfile
    ports:
      - 81:80
    networks:
      - backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Password.123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - USER_SECRETS_ID=0b37454a-7637-4cb5-86fb-7f3d1f6741ef
    volumes:
      - ~/.aspnet/https:/https:ro
      - $APPDATA/Microsoft/UserSecrets/$USER_SECRETS_ID:/root/.microsoft/usersecrets/$USER_SECRETS_ID
      - $HOME/.microsoft/usersecrets/$USER_SECRETS_ID:/root/.microsoft/usersecrets/$USER_SECRETS_ID

  mediscreen.patientapi:
    container_name: patient-api
    image: ${DOCKER_REGISTRY-}mediscreenpatientapi
    build:
      context: .
      dockerfile: Mediscreen.PatientAPI/Dockerfile
    ports:
      - 82:80
    networks:
      - backend         
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Password.123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ${ASPNET_DB_HOST}
      - ${ASPNET_DB_PORT}
      - ${ASPNET_DB_NAME}
      - USER_SECRETS_ID=89782eda-456a-472a-8aa9-72288bb8c2dc
    volumes:
      - ~/.aspnet/https:/https:ro
      - $APPDATA/Microsoft/UserSecrets/$USER_SECRETS_ID:/root/.microsoft/usersecrets/$USER_SECRETS_ID
      - $HOME/.microsoft/usersecrets/$USER_SECRETS_ID:/root/.microsoft/usersecrets/$USER_SECRETS_ID
      
  mediscreen.historyapi:
    container_name: history-api
    image: ${DOCKER_REGISTRY-}mediscreenhistoryapi
    build:
      context: .
      dockerfile: Mediscreen.HistoryAPI/Dockerfile
    ports:
      - 83:80
    networks:
      - backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Password.123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ${ASPNET_DB_HOST}
      - ${ASPNET_DB_PORT}
      - ${ASPNET_DB_NAME}
      - USER_SECRETS_ID=820ea045-4298-4817-b31f-228364fae513
    volumes:
      - ~/.aspnet/https:/https:ro
      - $APPDATA/Microsoft/UserSecrets/$USER_SECRETS_ID:/root/.microsoft/usersecrets/$USER_SECRETS_ID
      - $HOME/.microsoft/usersecrets/$USER_SECRETS_ID:/root/.microsoft/usersecrets/$USER_SECRETS_ID
      
  mediscreen.assessmentapi:
    container_name: assessment-api
    image: ${DOCKER_REGISTRY-}mediscreenassessmentapi
    build:
      context: .
      dockerfile: Mediscreen.AssessmentAPI/Dockerfile
    ports:
      - 84:80
    networks:
      - backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Password.123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ${ASPNET_DB_HOST}
      - ${ASPNET_DB_PORT}
      - ${ASPNET_DB_NAME}
      - USER_SECRETS_ID=ca4170af-bd13-457e-89b5-98882a4dc44e
    volumes:
      - ~/.aspnet/https:/https:ro
      - $APPDATA/Microsoft/UserSecrets/$USER_SECRETS_ID:/root/.microsoft/usersecrets/$USER_SECRETS_ID
      - $HOME/.microsoft/usersecrets/$USER_SECRETS_ID:/root/.microsoft/usersecrets/$USER_SECRETS_ID

  mediscreen.webapp:
    container_name: webapp-api
    image: ${DOCKER_REGISTRY-}mediscreenwebapp
    build:
      context: .
      dockerfile: Mediscreen.WebApp/Dockerfile
    ports:
      - 8080:8080
      - 443:443
    networks:
      - backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Password.123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ApiGateway=http://${GATEWAY_HOST}:${GATEWAY_PORT}/
      - USER_SECRETS_ID=22a797d4-7b13-4780-abd0-74f5e2994ef3
    volumes:
      - ~/.aspnet/https:/https:ro
      - $APPDATA/Microsoft/UserSecrets/$USER_SECRETS_ID:/root/.microsoft/usersecrets/$USER_SECRETS_ID
      - $HOME/.microsoft/usersecrets/$USER_SECRETS_ID:/root/.microsoft/usersecrets/$USER_SECRETS_ID

  redis:
    image: redis